name: pages build and deployment
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: 配置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 安装依赖
        run: npm install
      - name: 生成博客静态页面
        run: |
          hexo clean
          hexo generate
      - name: 上传网页文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署网站
        id: deployment
        uses: actions/deploy-pages@v4
